name: Ethical Hacking Workflow

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install nmap
          pip install johnny

      - name: Run Nmap
        run: |
          nmap -sV target_ip

      - name: Run John the Ripper
        run: |
          john --wordlist=password.lst
